version: '3.5'
services:
  landing-page:
    image: registry.anderswind.dk/resolved-landingpage:initial
    container_name: landing-page
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_proxy'
      - 'traefik.backend=landing-page'
      - 'traefik.frontend.rule=Host:resolved.site,www.resolved.site'
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
